export const buttonSizes = {
  small: {
    fontSize: "var(--logile-size-body)",
    fontWeight: "var(--logile-weight-400)",
    paddingLeft: "var(--space-xl)",
    paddingRight: "var(--space-xl)",
    paddingTop: "var(--space-xs)",
    paddingBottom: "var(--space-xs)",
    borderRadius: "var(--radius-s)",
    height: "var(--size-8)",
  },
  medium: {
    fontSize: "var(--logile-size-body)",
    fontWeight: "var(--logile-weight-400)",
    paddingLeft: "var(--space-xl)",
    paddingRight: "var(--space-xl)",
    paddingTop: "var(--space-s)",
    paddingBottom: "var(--space-s)",
    borderRadius: "var(--radius-s)",
    height: "var(--size-9)",
  },
  large: {
    fontSize: "var(--logile-size-body)",
    fontWeight: "var(--logile-weight-400)",
    paddingLeft: "var(--space-xl)",
    paddingRight: "var(--space-xl)",
    paddingTop: "var(--space-m)",
    paddingBottom: "var(--space-m)",
    borderRadius: "var(--radius-m)",
    height: "var(--size-10)",
  },
};
