import type { TemplateLibraryTableRowType } from "./types";
import type { PaginatedResponse } from '../../core/types/pagination.type';

export const demoTableData2 : unknown[] = [
  {
    template_icon: { 
        type: 'Assigned',
    },
    template_name: { 
        name: '5-S Audit All Departments- 5S Certification Audits',
        type: 'Audit org',
        status: 'Assigned',
    },
    template_id: 'TT-59141',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  {
    template_icon: { 
        type: 'Checklist',
    },
    template_name: { 
        name: 'Cut Fruit/Cut Melon Presentation',
        type: 'Checklist',
        status: 'Assigned',
    },
    template_id: 'TT-60142',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  {
    template_icon: { 
        type: 'Checklist',
    },
    template_name: { 
        name: 'D2 LA County Maximum Occupancy- 031521',
        type: 'Checklist',
        status: 'Assigned',
    },
    template_id: 'TT-71143',
    created: '05/26/21',
    last_modified: '12/01/22',
  },
  
];

export const folderTreeData = {
    "success": true,
    "message": "Tags fetched successfully for role: ADMIN",
    "data": [
        {
            "tagId": 23,
            "tagName": "Templates",
            "tagType": "Task_Library",
            "tagSort": null,
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": [
                {
                    "tagId": 2020,
                    "tagName": "Nathaniel example",
                    "tagType": "Message_Board_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": null,
                    "children": [
                        {
                            "tagId": 2023,
                            "tagName": "test",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 101,
                    "tagName": " *Assigned Tasks*",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 3003,
                            "tagName": "Henry Task template Test",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": true,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2018,
                    "tagName": ".Queue Management",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3001,
                    "tagName": "Customer Tasks",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3005,
                    "tagName": "Investigation",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3006,
                    "tagName": "Heartbeat",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3009,
                    "tagName": "3.0 Connect Tests",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 3010,
                    "tagName": "Test Templates",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 3011,
                            "tagName": "Jens Tests",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 3012,
                    "tagName": "UI_TESTING",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2003,
                    "tagName": "Demo",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 1013,
                            "tagName": "Alex Lee Demo Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2004,
                            "tagName": "Client examples",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": [
                                {
                                    "tagId": 3013,
                                    "tagName": "Cleaning floor",
                                    "tagType": "Task_Library",
                                    "tagSort": null,
                                    "tagLevel": 3,
                                    "isPublic": true,
                                    "isPrivate": true,
                                    "isHidden": true,
                                    "isNoShow": false,
                                    "reportType": null,
                                    "isExpanded": true,
                                    "children": []
                                }
                            ]
                        },
                        {
                            "tagId": 2005,
                            "tagName": "Ross",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2007,
                            "tagName": "Albertsons",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2009,
                            "tagName": "Scotmid",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2010,
                            "tagName": "Heinen's",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2026,
                            "tagName": "Product updates",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3004,
                            "tagName": "Grind",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3008,
                            "tagName": "Inventory",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2011,
                    "tagName": "Archive",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": true,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 116,
                    "tagName": "Standard Templates",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 117,
                            "tagName": "Operational Processes",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 118,
                            "tagName": "Compliance Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 119,
                            "tagName": "Performance Mangement",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 121,
                            "tagName": "External Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 123,
                            "tagName": "Corporate Quick Tasks",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 1019,
                            "tagName": "Incident Management",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2001,
                            "tagName": "Tickets (demo)",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2002,
                            "tagName": "Food safety",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": [
                                {
                                    "tagId": 2025,
                                    "tagName": "Sanitation",
                                    "tagType": "Task_Library",
                                    "tagSort": null,
                                    "tagLevel": 3,
                                    "isPublic": true,
                                    "isPrivate": true,
                                    "isHidden": true,
                                    "isNoShow": false,
                                    "reportType": null,
                                    "isExpanded": false,
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "tagId": 2019,
                    "tagName": ".Store Conditions",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2017,
                    "tagName": ".Food Safety",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 120,
                    "tagName": "Standard Templates",
                    "tagType": "Message_Board_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": null,
                    "children": [
                        {
                            "tagId": 2021,
                            "tagName": "New Folder",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        },
                        {
                            "tagId": 2022,
                            "tagName": "test directory",
                            "tagType": "Message_Board_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": false,
                            "isHidden": false,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": null,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2015,
                    "tagName": "Incident Management",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2006,
                    "tagName": "Videos",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                },
                {
                    "tagId": 2014,
                    "tagName": "Food Safety resources",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": [
                        {
                            "tagId": 2008,
                            "tagName": "Food Safety Training",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 2024,
                            "tagName": "Sensor Management",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3002,
                            "tagName": "Testing ( do not delete)",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        },
                        {
                            "tagId": 3007,
                            "tagName": "PS_Sandbox",
                            "tagType": "Task_Library",
                            "tagSort": null,
                            "tagLevel": 2,
                            "isPublic": true,
                            "isPrivate": true,
                            "isHidden": true,
                            "isNoShow": false,
                            "reportType": null,
                            "isExpanded": false,
                            "children": []
                        }
                    ]
                },
                {
                    "tagId": 2016,
                    "tagName": "Store operations Solution",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": null,
                    "isExpanded": false,
                    "children": []
                }
            ]
        },
        {
            "tagId": 3000,
            "tagName": "IMS Tasks",
            "tagType": "Task_Library",
            "tagSort": "000|000|000",
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": []
        },
        {
            "tagId": 76,
            "tagName": "Report Task",
            "tagType": "Task_Library",
            "tagSort": "000|000|000",
            "tagLevel": 1,
            "isPublic": true,
            "isPrivate": true,
            "isHidden": true,
            "isNoShow": false,
            "reportType": null,
            "isExpanded": true,
            "children": [
                {
                    "tagId": 77,
                    "tagName": "Execution",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 103,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 78,
                    "tagName": "Score",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 9,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 79,
                    "tagName": "Compliance",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 104,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 80,
                    "tagName": "Detail",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 10,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 122,
                    "tagName": "Metric",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 105,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 1001,
                    "tagName": "Sales and Labor",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": -1,
                    "isExpanded": null,
                    "children": []
                },
                {
                    "tagId": 1017,
                    "tagName": "Metric Distinct",
                    "tagType": "Task_Library",
                    "tagSort": null,
                    "tagLevel": 1,
                    "isPublic": true,
                    "isPrivate": true,
                    "isHidden": true,
                    "isNoShow": false,
                    "reportType": 106,
                    "isExpanded": null,
                    "children": []
                },
              ]
            }
    ],
    pagination: { currentPage: 1, pageSize: 10, totalPages: 1, totalItems: 100 }
  }

export const demoTableData: PaginatedResponse<TemplateLibraryTableRowType[]> = {
    success: true,
    message: 'Success',
    data: [
        {
            "templateId": 1894,
            "tagId": 2002,
            "templateName": "Cook Log (>165) (from launch task)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2019-07-10T17:20:52.223",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 1973,
            "tagId": 2005,
            "templateName": "Discard product",
            "tagType": "Corrective actions",
            "status": null,
            "createdTime": "2017-11-16T13:35:28",
            "lastModifiedTime": "2019-08-01T15:52:25.28",
            "iconName": "VIOLATION",
            "iconColour": "d15c58"
        },
        {
            "templateId": 1981,
            "tagId": 2006,
            "templateName": "Cool Down Interval - 2 hr.",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-01-15T16:46:34.95",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2203,
            "tagId": 2009,
            "templateName": "Hot Bar Temp Check (location scan)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2018-09-26T22:30:49.677",
            "lastModifiedTime": "2020-07-17T18:51:41.612",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2205,
            "tagId": 2010,
            "templateName": "Cook Log (>90)",
            "tagType": "Logs",
            "status": null,
            "createdTime": "2017-11-16T13:24:42",
            "lastModifiedTime": "2020-08-05T10:23:10.096",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2207,
            "tagId": 2011,
            "templateName": "Two-Hour Hot Hold Interval (>80)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-07-17T22:17:45.636",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
        {
            "templateId": 2208,
            "tagId": 2012,
            "templateName": "Two-Hour Hot Hold Interval (subsequent)",
            "tagType": "Temperature Check",
            "status": null,
            "createdTime": "2017-11-16T13:33:18",
            "lastModifiedTime": "2020-07-17T22:18:03.692",
            "iconName": "v15-Shop-supply",
            "iconColour": "#bd9721"
        },
    ],
    pagination: { currentPage: 1, pageSize: 10, totalPages: 1, totalItems: 100 }
}
