name: deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy to (QA1 or QA2)"
        required: true
        default: QA1
        type: choice
        options:
          - QA1
          - QA2
      branch:
        description: "Branch to deploy"
        required: true
        default: dev

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npx vite build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          target-folder: /${{ github.event.inputs.env }}
          folder: dist
